# Generated by Django 4.2.4 on 2025-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_topic_created_by_alter_translation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
