# Generated by Django 4.2.4 on 2025-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_topic_descriptions_vocabulary_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.CharField(blank=True, choices=[('n', 'Noun'), ('v', 'Verb'), ('adj', 'Adj'), ('adv', 'Adv'), ('prep', 'Prep')], default=None, max_length=10, null=True),
        ),
    ]
