# Generated by Django 4.2.4 on 2025-03-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_translation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
