# Generated by Django 4.2.4 on 2025-04-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_translation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='vocabulary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flashcards.vocabulary'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['language', 'vocabulary'], name='flashcards__languag_88ee00_idx'),
        ),
    ]
