# Generated by Django 4.2.4 on 2025-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_alter_translation_vocabulary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio',
            field=models.BinaryField(null=True),
        ),
    ]
