# Generated by Django 4.2.4 on 2025-06-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_vocabulary_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='flashcards.topic'),
        ),
    ]
