# Generated by Django 4.2.4 on 2025-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_alter_vocabulary_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='learning_language',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vn', 'Vietnamese'), ('ja', 'Japanese')], default='en', max_length=10),
        ),
    ]
