# Generated by Django 4.2.4 on 2025-09-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_usersalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersalt',
            name='salt',
            field=models.CharField(max_length=200),
        ),
    ]
