# Generated by Django 4.2.4 on 2025-11-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_alter_usersalt_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/topics'),
        ),
    ]
