# Generated by Django 4.2.4 on 2025-11-20 02:56

from django.db import migrations, models
import flashcards.models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_topic_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=flashcards.models.topic_image_upload_to),
        ),
    ]
