# Generated by Django 4.2.4 on 2025-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_alter_topic_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('privite', 'Privite'), ('public', 'Public')], default='privite', max_length=15),
        ),
    ]
