# Generated by Django 4.2.4 on 2025-11-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=15),
        ),
    ]
