# Generated by Django 4.2.4 on 2026-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_copy_all_users_data_from_flashcards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
