server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # React static assets
    location /static/ {
        try_files $uri =404;
    }
}

